name: AutoDeploy

on:
  push:
    branches:
      - master

jobs:
  release-app:
    runs-on: self-hosted

    steps:
      # Ambil kode dari repositori
      - name: Ambil kode sumber
        uses: actions/checkout@v3

      # Siapkan environment Node.js
      - name: Siapkan Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependensi & build project
        run: |
          npm ci
          npm run build

      # Siapkan environment PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, curl, gd, mysql

      - name: Optimalkan aplikasi Laravel
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan livewire:publish --assets

      # Upload hasil build ke server
      - name: Sinkronisasi ke direktori server
        run: |
          rsync -avz --delete \
            --exclude='.env' --exclude='.git/' \
            --no-perms --no-group --omit-dir-times \
            ${{ github.workspace }}/ /home/jogjacare10.my.id/public_html/

      # Buat symbolic link storage
      - name: Finalisasi & tautan storage
        run: |
          cd /home/jogjacare10.my.id/public_html
          rm -f public/storage
          php artisan storage:link
