name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, curl, gd, mysql

      - run: |
          composer install --no-dev --optimize-autoloader
          php artisan livewire:publish --assets

      - name: Deploy to public_html
        run: |
          rsync -av --delete --exclude='.env' --exclude='.git/' \
          --no-perms --no-group --omit-dir-times \
          ${{ github.workspace }}/ /home/jogjacare10.my.id/public_html/

      - run: |
          cd /home/jogjacare10.my.id/public_html
          rm -f public/storage
          php artisan storage:link
